[package]
name = "chess"
version = "0.1.0"
edition = "2024"
autobins = false

[dependencies]
tracing = "0.1.43"
tracing-flame = "0.2.0"
tracing-subscriber = "0.3.22"

[[bin]]
name = "my_project"
path = "src/main.rs"
